cluster_instances:
  - id: 1
    pre_process_cmd: "wget google.com"
    post_process_cmd: "wget google.com"
    hosts:
      - "127.0.0.1"
    benchmark:
      - id: 101
        type: "NPmpi"
        pre_cmd_exec: "echo hello_world_pre >> pre_cmd_exec"   # Optional
        post_cmd_exec: "echo hello_world_post >> post_cmd_exec" # Optional
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--bind-to none"
        target_nodes:
          - "127.0.0.1"
        instances: 2
      - id: 102
        type: "custom"
        pre_cmd_exec: "echo hello_world_pre_custom >> pre_cmd_exec"   # Optional
        post_cmd_exec: "echo hello_world_post_custom >> post_cmd_exec" # Optional
        command_line: "sysbench cpu run"
        target_nodes:
          - "127.0.0.1"
        instances: 5

  - id: 2
    hosts:
      - "127.0.0.1"
    pre_process_cmd: "echo hello_world_pre >> pre_process_cmd"
    post_process_cmd: "echo hello_world_post >> post_process_cmd"
    benchmark:
      - id: 101
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--allow-run-as-root"
        target_nodes:
          - "127.0.0.1"
      - id: 102
        type: "xhpl"
        pre_cmd_exec: "curl https://pastebin.com/raw/cxK2CfcJ -o HPL.dat"   # Optional
        mpi_processes: 1
        mpi_hosts:
          - "127.0.0.1:1"
        mpi_args: ""
        target_nodes:
          - "127.0.0.1"
