cluster_instances:   
  - name: "netpipe_inter_8cpu_1i"
    pre_process_cmd: "bash /script.sh 8 16384 1 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:1"
          - "192.168.1.251:1"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe_inter_4cpu_1i"
    pre_process_cmd: "bash /script.sh 4 8192 1 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:1"
          - "192.168.1.251:1"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe_inter_2cpu_1i"
    pre_process_cmd: "bash /script.sh 2 4096 1 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:1"
          - "192.168.1.251:1"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe_inter_1cpu_1i"
    pre_process_cmd: "bash /script.sh 1 2048 1 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:1"
          - "192.168.1.251:1"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
        instances: 1      
