cluster_instances:   
  - name: "netpipe-single-local-8cpu"
    pre_process_cmd: "bash /script.sh 8 16384 2 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "192.168.1.30:1"
          - "192.168.1.31:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe-single-local-4cpu"
    pre_process_cmd: "bash /script.sh 4 8192 2 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "192.168.1.30:1"
          - "192.168.1.31:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe-single-local-2cpu"
    pre_process_cmd: "bash /script.sh 2 4096 2 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "192.168.1.30:1"
          - "192.168.1.31:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1      
  - name: "netpipe-single-local-1cpu"
    pre_process_cmd: "bash /script.sh 1 2048 2 && sleep 60"
    post_process_cmd: ""
    run_count: 5
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "192.168.1.30:1"
          - "192.168.1.31:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1      
