cluster_instances:
  - id: 1
    run_count: 30
    pre_process_cmd: ""
    post_process_cmd: ""
    hosts:
      - "127.0.0.1"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "127.0.0.1"
        instances: 8
  - id: 2
    pre_process_cmd: ""
    post_process_cmd: ""
    run_count: 30
    hosts:
      - "127.0.0.1"
      - "192.168.1.251"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:1"
          - "192.168.1.251:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "127.0.0.1"
        instances: 8    