# This file contains the configuration for the NetPipe benchmark.

cluster_instances:
  - id: 1
    pre_process_cmd: "bash /script.sh 1 2048 8 && sleep 60"
    post_process_cmd: ""
    hosts:
      - "192.168.1.30"
      - "192.168.1.31"
      - "192.168.1.32"
      - "192.168.1.33"
      - "192.168.1.34"
      - "192.168.1.35"
      - "192.168.1.36"
      - "192.168.1.37"
      - "127.0.0.1"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
          - "192.168.1.32"
          - "192.168.1.33"
          - "192.168.1.34"
          - "192.168.1.35"
          - "192.168.1.36"
          - "192.168.1.37"
        instances: 1

  - id: 2
    pre_process_cmd: "bash /script.sh 2 4096 4 && sleep 60"
    post_process_cmd: ""
    hosts:
      - "192.168.1.30"
      - "192.168.1.31"
      - "192.168.1.32"
      - "192.168.1.33"
      - "127.0.0.1"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
          - "192.168.1.32"
          - "192.168.1.33"
        instances: 2
  
  - id: 3
    pre_process_cmd: "bash /script.sh 4 8192 2 && sleep 60"
    post_process_cmd: ""
    hosts:
      - "192.168.1.30"
      - "192.168.1.31"
      - "127.0.0.1"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
        instances: 4

  - id: 4
    pre_process_cmd: "bash /script.sh 8 16384 1 && sleep 60"
    post_process_cmd: ""
    hosts:
      - "192.168.1.30"
      - "127.0.0.1"
    benchmark:
      - id: 100
        type: "NPmpi"
        mpi_processes: 2
        mpi_hosts:
          - "127.0.0.1:2"
        mpi_args: "--oversubscribe --bind-to none"
        target_nodes:
          - "192.168.1.30"
        instances: 8      