# This file is part of the competitive HPL benchmark suite.
cluster_instances:    
  - name: "HPL-COMP-8VM"
    pre_process_cmd: "bash /script.sh 1 2048 8 && sleep 60"
    run_count: 3
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COMP.conf -O HPL.dat"
        command_line: "xhpl"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
          - "192.168.1.32"
          - "192.168.1.33"
          - "192.168.1.34"
          - "192.168.1.35"
          - "192.168.1.36"
          - "192.168.1.37"
        instances: 1
  - name: "HPL-COMP-4VM"
    pre_process_cmd: "bash /script.sh 2 4096 4 && sleep 60"
    run_count: 3
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COMP.conf -O HPL.dat"
        command_line: "xhpl"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
          - "192.168.1.32"
          - "192.168.1.33"
        instances: 2
  - name: "HPL-COMP-2VM"
    pre_process_cmd: "bash /script.sh 4 8192 2 && sleep 60"
    run_count: 3
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COMP.conf -O HPL.dat"
        command_line: "xhpl"
        target_nodes:
          - "192.168.1.30"
          - "192.168.1.31"
        instances: 4
  - name: "HPL-COMP-1VM"
    pre_process_cmd: "bash /script.sh 8 16384 1 && sleep 60"
    run_count: 3
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COMP.conf -O HPL.dat"
        command_line: "xhpl"
        target_nodes:
          - "192.168.1.30"
        instances: 8