# This file is part of the cooperative HPL benchmark suite.
cluster_instances:    
  - name: "HPL-COOP-8VM"
    pre_process_cmd: "bash /script.sh 1 2048 8 && sleep 60"
    run_count: 5
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COOP.conf -O HPL.dat"
        type: "xhpl"
        mpi_processes: 8
        mpi_hosts:
          - "192.168.1.30:1"
          - "192.168.1.31:1"
          - "192.168.1.32:1"
          - "192.168.1.33:1"
          - "192.168.1.34:1"
          - "192.168.1.35:1"
          - "192.168.1.36:1"
          - "192.168.1.37:1"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1   
  - name: "HPL-COOP-4VM"
    pre_process_cmd: "bash /script.sh 2 4096 4 && sleep 60"
    run_count: 5
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COOP.conf -O HPL.dat"
        type: "xhpl"
        mpi_processes: 8
        mpi_hosts:
          - "192.168.1.30:2"
          - "192.168.1.31:2"
          - "192.168.1.32:2"
          - "192.168.1.33:2"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1   
  - name: "HPL-COOP-2VM"
    pre_process_cmd: "bash /script.sh 4 8192 2 && sleep 60"
    run_count: 5
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COOP.conf -O HPL.dat"
        type: "xhpl"
        mpi_processes: 8
        mpi_hosts:
          - "192.168.1.30:4"
          - "192.168.1.31:4"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1   
  - name: "HPL-COOP-1VM"
    pre_process_cmd: "bash /script.sh 8 16384 1 && sleep 60"
    run_count: 5
    benchmark:
      - id: 100
        pre_process_cmd: "wget https://raw.githubusercontent.com/aurelienizl/hpc-research/refs/heads/v2/src/ressources/configs/hpl/HPL_COOP.conf -O HPL.dat"
        type: "xhpl"
        mpi_processes: 8
        mpi_hosts:
          - "192.168.1.30:8"
        mpi_args: "--oversubscribe --bind-to none --mca plm_rsh_agent \"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
        target_nodes:
          - "192.168.1.30"
        instances: 1
